### PR TITLE
Make balance act as clicking on 100%

### PR DESCRIPTION
**Pull request by dgornjakovic**
image

### CODE REVIEW

**Comment by clementbalestrat** [comment]
@dgornjakovic thanks! Before we can have a look at it can you please remove the `.gitignore` changes and fix your formatter? Lots of unnecessary indents in your changes.

**Comment by dgornjakovic** [comment]
Reverted .gitignore and fixed formatting

**Comment by dgornjakovic** [comment]
@clementbalestrat Please review the adapted changes.

**Comment by clementbalestrat** [comment]
@dgornjakovic sorry for the delay. We were in the middle of a big code refactoring/release. I'm going to close the PR as the file you modified is not up-to-date with the latest changes but will add your update in the next release.

**Pull request closed without merging**
