### PR TITLE
V2 order book

### PR DESCRIPTION
**Pull request by vmkcom**

### CODE REVIEW

**Comment by clementbalestrat** [comment]
@vmkcom the merge conflict is pretty bad. 

I reckon we should split the tabs content in different files?

1 file for live transactions and 1 file for "my trade" and "all trades".

**Comment by vmkcom** [comment]
Agree, ok, I'll do it and merge your branch to me first

**Comment by clementbalestrat** [comment]
@vmkcom sounds good!

**Comment by clementbalestrat** [comment]
@vmkcom did you have time to have a look at it?

**Comment by vmkcom** [comment]
Not yet but I can do it today if it still relevant

**Comment by clementbalestrat** [comment]
Yep! Still relevant

**Comment by vmkcom** [comment]
@clementbalestrat, have a look at it please, I extracted my updates into PastTransaction table, it's working now, although you might want me to change paging / styles

**Comment by clementbalestrat** [comment]
Thanks @vmkcom !

**Pull request merged**
