### PR TITLE
76 aggregated data

### PR DESCRIPTION
**Pull request by bachstatter**
Add min, max and change for the last 24h
image

#76

### CODE REVIEW

**Comment by clementbalestrat** [comment]
@bachstatter I'm confused on what `lastDayData` does?

Also 24h change, high and low shouldn't update when changing chart timeframe? From 1D to 1W for example?

You should request last 24h data from `snxData` in another function to make sure you're dealing with the correct timeframe.

**Comment by clementbalestrat** [comment]
Also would be nice to have red when negative and green when positive :)

**Comment by bachstatter** [comment]
We always request the 24h data on load. It's the initial state.  So I stored that response in a different state variable that only gets set the first time we receive  data.  Maybe a little hacky. But otherwise we will do two request doing the exact same thing on load. 

Does that make sense?

I'll add some colors 👍

**Comment by bachstatter** [comment]
Saw you merged this one, let me know if I should to an extra request, or if you're happy with the current implementation.

I've added colors to the v2 branch directly

**Comment by clementbalestrat** [comment]
@bachstatter I just realised: my point with the `lastDayData` confusion was it's not being used anywhere in the code.

**Comment by clementbalestrat** [comment]
This is why the data is still updating when timeframe are changed.

**Pull request merged**
