### PR TITLE
fixed typo in URL synthetipx.io > synthetix.io

### PR DESCRIPTION
**Pull request by Qaaj**
Litepaper: 'https://www.synthetipx.io/litepaper' > 		Litepaper: 'https://www.synthetix.io/litepaper',

### CODE REVIEW

**Comment by evgenyboxer** [comment]
hey @Qaaj thank you for your PR. could you please change the base branch to dev. Thx!

**Comment by Qaaj** [comment]
done @evgenyboxer!

**Comment by evgenyboxer** [comment]
@Qaaj It seems to include package-lock changes, etc.. perhaps its best to just start off a fresh dev branch, and apply the changes you made on top of it so that we only merge that in.

**Comment by evgenyboxer** [comment]
Hey @Qaaj I'm going to close it, and merge this fix in a new PR. Thank you for reporting this!

**Comment by Qaaj** [comment]
Oh oops, yes I messed up haha.. I shouldn't push code before breakfast.  Cheers!

**Pull request closed without merging**
